# Generated by Django 2.2 on 2020-04-07 08:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pets', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='pet',
            table='pets',
        ),
    ]
