# Generated by Django 2.2 on 2020-04-07 08:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pets', '0002_auto_20200407_0809'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='pet',
            options={'ordering': ['-updated_at']},
        ),
    ]
