# Generated by Django 2.2 on 2020-04-07 08:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pets', '0003_auto_20200407_0811'),
    ]

    operations = [
        migrations.CreateModel(
            name='Host',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='修改时间')),
                ('name', models.CharField(max_length=64, verbose_name='主人名字')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='pet',
            name='hosts',
            field=models.ManyToManyField(to='pets.Host'),
        ),
    ]
