# Generated by Django 2.2 on 2020-04-07 08:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pets', '0004_auto_20200407_0823'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='host',
            table='hosts',
        ),
    ]
